
name = "Materialdashboard"
uuid = "1b08a953-4be3-4667-9a23-5a8890fc84c9"
authors = ["Flo Vouin <florent.vouin@gmail.com>"]
version = "0.2.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
