name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          npm install
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Lint
        run: ./node_modules/.bin/eslint --ext .ts,.js .
      - name: Generate components
        run: npm run generate
      - name: Build
        run: |
          . venv/bin/activate
          npm run build
          python setup.py sdist bdist_wheel
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          . venv/bin/activate
          pip install --upgrade twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
